flask_email/app/main/models.py
from peewee import *


database_proxy = DatabaseProxy()


class BaseModel(Model):
    class Meta:
        database = database_proxy


class User(BaseModel):
    name = CharField(max_length=100)
    email = CharField(max_length=150, unique=True, index=True)

flask_email/app/main/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, EmailField, SubmitField
from wtforms.validators import DataRequired, Length


class GenerateDataForm(FlaskForm):
    submit = SubmitField('Generate')


class NameForm(FlaskForm):
    name = StringField(
        'What is your name?',
        validators=[DataRequired(), Length(3, 100)],
        render_kw={'placeholder': 'Full name'}
    )
    email = EmailField(
        'What is your email?',
        validators=[DataRequired(), Length(10, 150)],
        render_kw={'placeholder': 'Email'}
    )
    submit = SubmitField('Add')

flask_email/app/__init__.py
from flask import Flask
from flask_wtf.csrf import CSRFProtect
from flask_bootstrap import Bootstrap
from flask_moment import Moment
from peewee import SqliteDatabase

from app.config import config
from app.error_handlers import page_not_found, internal_server_error
from app.main.models import database_proxy, User


def create_app(config_name='default'):
    app = Flask(__name__)
    app.static_folder = 'static'
    app.config.from_object(config[config_name])

    app.register_error_handler(404, page_not_found)
    app.register_error_handler(500, internal_server_error)

    db = SqliteDatabase(app.config['DB_NAME'])
    database_proxy.initialize(db)
    db.create_tables([User])

    csrf = CSRFProtect(app)
    csrf.init_app(app)

    Bootstrap(app)

    moment = Moment(app)
    moment.init_app(app)

    from app import main
    from app import forum

    app.register_blueprint(main.main)
    app.register_blueprint(forum.forum)

    return app

flask_email/app/forum/__init__.py
from flask import Blueprint

forum = Blueprint('forum', __name__)

flask_email/app/main/__init__.py
from flask import Blueprint

main = Blueprint('main', __name__)

from app.main import routes

flask_email/app/main/routes.py
from flask import render_template, redirect, url_for, flash, request
from datetime import datetime

from app.main import main
from app.main.forms import NameForm, GenerateDataForm
from app.main.models import User
from generate_data.main import main as generate_data
from generate_data.data import emails_data


@main.route('/', methods=['POST', 'GET'])
def index():
    """Home page"""
    form = GenerateDataForm()

    if form.validate_on_submit():
        if not User.select():
            emails = generate_data(emails_data)
            for name, email in emails:
                user = User(name=name, email=email)
                user.save()
            flash('Database filled with test data')
        else:
            flash('Database is not empty')

    return render_template(
        'index.html',
        title='Home page',
        current_time=datetime.utcnow(),
        form=form
    )


@main.route('/email', methods=['POST', 'GET'])
def add_email():
    """Add name and email form page"""
    form = NameForm()

    if form.validate_on_submit():
        name = form.name.data
        email = form.email.data
        message = f'User with name {name} already registered'
        if not User.select().where(User.email == email):
            user = User(name=name, email=email)
            user.save()
            message = f'User with name {name} just registered'

        flash(message)
        return redirect(url_for('main.add_email'))

    return render_template(
        'main/email.html',
        title='Register user',
        form=form
    )


@main.route('/show_emails')
def show_emails():
    """Show user information"""
    users = User.select()
    return render_template(
        'main/show_emails.html',
        title='Show users',
        users=users
    )


@main.route('/delete_emails', methods=['POST'])
def delete_emails():
    """Delete selected users"""
    if request.method == 'POST':
        message = 'Deleted: '
        selectors = list(map(int, request.form.getlist('selectors')))

        if not selectors:
            flash('Nothing to delete')
            return redirect(url_for('main.show_emails'))

        for selector in selectors:
            user = User.get(User.id == selector)
            message += f'{user.email} '
            user.delete_instance()

        flash(message)
        return redirect(url_for('main.show_emails'))

flask_email/app/templates/_base.html
{% extends "bootstrap/base.html" %}

{% block head %}
{{ super() }}
    <link rel="shortcut icon" href="{{ url_for('static', filename='img/favicon.png') }}"
        type="image/x-icon">
    <link rel="icon" href="{{ url_for('static', filename='img/favicon.png') }}"
        type="image/x-icon">
{% endblock %}

{% block title %}{% endblock %}

{% block navbar %}
<div class="navbar navbar-inverse" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle"
                data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/">Web app</a>
        </div>
        <div class="navbar-collapse collapse">
        <ul class="nav navbar-nav">
        <li><a class='action' href="{{ url_for('main.index') }}">Home</a></li>
        <li><a class='action' href="{{ url_for('main.add_email') }}">Add user</a></li>
        <li><a class='action' href="{{ url_for('main.show_emails') }}">Show users</a></li>
        </ul>
        </div>
    </div>
</div>
{% endblock %}

{% block content %}
<div class="container">
    {% block page_content %}{% endblock %}
</div>
{% endblock %}

{% block scripts %}
{{ super() }}
    {{ moment.include_moment() }}
    <script src="https://cdn.jsdelivr.net/npm/@mojs/core"></script>
    <script type="text/javascript" src="{{ url_for('static', filename='js/links.js') }}"></script>
    <script type="text/javascript" src="{{ url_for('static', filename='js/select.js') }}"></script>
{% endblock %}

flask_email/app/templates/error.html
{% extends '_base.html' %}

{% block title %}
  {{ title }}
{% endblock %}


{% block page_content %}
  <div class="page-header">
    <h3> {{ error }} </h3>
  </div>
{% endblock %}

flask_email/app/templates/index.html
{% extends '_base.html' %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}
  {{ title }}
{% endblock %}

{% block page_content %}

<div class="page-header">
  <h1>Welcome to the web application.</h1>
</div>
<h3>Generate test data</h3>
{% include 'messages.html' %}
<form action="{{ url_for('main.index') }}" method="post">
  {{ form.csrf_token }}
  {{ wtf.form_field(form.submit) }}
</form>
<hr>

<p>The local date and time is {{ moment(current_time).format('MMMM Do YYYY, H:mm:ss') }}.</p>
<p>That was {{ moment(current_time).fromNow(refresh=True) }}</p>

{% endblock page_content %}

flask_email/app/templates/main/add_email.html
{% extends '_base.html' %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}
  {{ title }}
{% endblock title %}

{% block page_content %}
    <div class="page-header">
        <h1>Register user</h1>
    </div>
    {% include 'messages.html' %}
    <form action="{{ url_for('main.add_email') }}" method="POST">
        {{ form.csrf_token }}
        {{ wtf.form_field(form.name) }}
        {{ wtf.form_field(form.email) }}
        {{ wtf.form_field(form.submit) }}
    </form>
{% endblock page_content %}

flask_email/app/templates/main/email.html
{% extends '_base.html' %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}
  {{ title }}
{% endblock title %}

{% block page_content %}
<div class="page-header">
    <h1>Register user</h1>
</div>
{% include 'messages.html' %}

<form action="{{ url_for('main.add_email') }}" method="POST">
    {{ form.csrf_token }}
    {{ wtf.form_field(form.name) }}
    {{ wtf.form_field(form.email) }}
    {{ wtf.form_field(form.submit) }}
</form>
{% endblock page_content %}

flask_email/app/templates/main/show_emails.html
{% extends '_base.html' %}

{% block title %}
  {{ title }}
{% endblock title %}

{% block page_content %}
<div class="page-header">
    <h1>Register user</h1>
</div>
{% include 'messages.html' %}

<button type="button" class="btn btn-primary" id="selectButton" onclick="toggle()">Select all</button>
<button type="submit" class="btn btn-danger" form="userForm">Delete</button>

<form action="{{ url_for('main.delete_emails') }}" method="post" id="userForm">
    <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>
    <div class="table-responsive">
        <table class="table table-hover table-striped" id="userTable">
            <thead>
            <tr>
                <th scope="col">Select</th>
                <th scope="col">ID</th>
                <th scope="col">Name</th>
                <th scope="col">Email</th>
            </tr>
            </thead>
            <tbody>
            {% for user in users %}
            <tr>
                <td>
                    <input type="checkbox" name="selectors" class="checkbox" value="{{ user.id }}"/>
                </td>
                <td>{{ user.id }}</td>
                <td>{{ user.name }}</td>
                <td>{{ user.email }}</td>
            </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
</form>

{% endblock page_content%}

flask_email/app/templates/messages.html
{% for message in get_flashed_messages() %}
    <div class="alert alert-warning" id="alert_block">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true" id="close_alert" onclick="closeAlert()">&times;</span>
        </button>
    {{ message }}
    </div>
{% endfor %}